export const CHANGE_PLAY_LIST = "CHANGE_PLAY_LIST";
export const CHANGE_PLAY_SEQUENCE = "CHANGE_PLAY_SEQUENCE";
export const CHANGE_CURRENT_INDEX = "CHANGE_CURRENT_INDEX";
export const CHANGE_CURRENT_SONG = "CHANGE_CURRENT_SONG";

export const CHANGE_LYRICS = "CHANGE_LYRICS";
