export const CHANGE_TOP_BANNER = "CHANGE_TOP_BANNER";
export const CHANGE_HOT_RECOMMENT = "CHANGE_HOT_RECOMMENT";
export const CHANGE_NEW_ALBUM = "CHANGE_NEW_ALBUM";
export const CHANGE_TOP_LIST = "CHANGE_TOP_LIST";
export const CHANGE_SETTLED_SINGER = "CHANGE_SETTLED_SINGER";
export const CHANGE_HOT_ANCHOR = "CHANGE_HOT_ANCHOR";
